#Base image
FROM node:alpine

#set working directory
WORKDIR '/app'

#copy package.json to successfully run npm install
COPY package.json .

#run yarn install
RUN yarn install

#copy rest of directory
COPY . .

#set initial command
CMD ["yarn","start"]
